version: '2'
services:
  postgres:
    image: eeacms/postgres:9.4-3.0
    labels:
      io.rancher.scheduler.affinity:host_label: ${POSTGRES_HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_ne: eea.europa.eu.postgres=yes
      eea.europa.eu.postgres: "yes"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_DBUSER: "${POSTGRES_DBUSER}"
      POSTGRES_DBPASS: "${POSTGRES_DBPASS}"
      POSTGRES_CONFIG: "${POSTGRES_CONFIG}"
      POSTGRES_CRONS: "${POSTGRES_CRONS}"
      TZ: "${TZ}"
    volumes:
    - data:/var/lib/postgresql/data
    - dump:/postgresql.backup
    - archive:/var/lib/postgresql/archive
volumes:
  data:
    driver: local
  dump:
    driver: ${NFS_VOLUME_DRIVER}
  archive:
    driver: ${NFS_VOLUME_DRIVER}
