.catalog:
  name: "Logcentral"
  version: "2.0.2-rancher1"
  description: "EEA Centralized logging based on Docker and Graylog2"
  questions:
    - variable: postfix_mtp_user
      description: "Select the mtp user"
      label: "MTP_USER"
      type: "string"
      required: true
    - variable: postfix_mtp_password
      description: "Select the mtp password"
      label: "MTP_PASS"
      type: "password"
      required: true
    - variable: graylog_root_password
      description: "Select the graylog root password. If you don't set this, it will be generated"
      label: "Graylog root password"
      type: "password"
      required: false
    - variable: graylog_secret
      description: "Select a secret to secure/pepper the stored user passwords. Generate one by using for example: pwgen -N 1 -s 96"
      label: "Graylog secret password"
      type: "string"
      required: true
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: "es/elasticsearch-client"
      required: true
      type: "service"
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: graylogspool=yes
    - variable: host_mongo_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: graylogmongo=yes
