elasticsearch-master:
  image: rancher/elasticsearch-conf:v0.5.0
  labels:
    io.rancher.sidekicks: elasticsearch-base-master,elasticsearch-datavolume-master
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-master
elasticsearch-datavolume-master:
  image: elasticsearch:2.2.1
  labels:
    elasticsearch.datanode.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes:
    - elasticsearch:/opt/rancher/bin
    - elasticsearch:/usr/share/elasticsearch/config
    - elasticsearch:/usr/share/elasticsearch/data
  entrypoint: /bin/true
elasticsearch-base-master:
  image: elasticsearch:2.2.1
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-master
  entrypoint:
    - /opt/rancher/bin/run.sh
  net: "container:elasticsearch-master"

elasticsearch-datanode:
  image: rancher/elasticsearch-conf:v0.5.0
  labels:
    io.rancher.sidekicks: elasticsearch-base-datanode,elasticsearch-datavolume-datanode
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-datanode
  links:
    - elasticsearch-master:es-master
elasticsearch-datavolume-datanode:
  image: elasticsearch:2.2.1
  labels:
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    elasticsearch.datanode.config.version: '0'
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  volumes:
    - logcentral:/opt/rancher/bin
    - logcentral:/usr/share/elasticsearch/config
    - logcentral:/usr/share/elasticsearch/data
  entrypoint: /bin/true
elasticsearch-base-datanode:
  image: elasticsearch:2.2.1
  labels:
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    elasticsearch.datanode.config.version: '0'
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-datanode
  links:
    - elasticsearch-master:es-master
  entrypoint:
    - /opt/rancher/bin/run.sh
  net: "container:elasticsearch-datanode"

elasticsearch-client:
  image: rancher/elasticsearch-conf:v0.5.0
  labels:
    io.rancher.sidekicks: elasticsearch-datavolume-client,elasticsearch-base-client
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
     io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-client
  links:
    - elasticsearch-master:es-master
elasticsearch-datavolume-client:
  image: elasticsearch:2.2.1
  labels:
    io.rancher.container.start_once: true
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    elasticsearch.datanode.config.version: '0'
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes:
    - logcentral:/usr/share/elasticsearch/config
    - logcentral:/usr/share/elasticsearch/data
    - logcentral:/opt/rancher/bin
  entrypoint: /bin/true
elasticsearch-base-client:
  image: elasticsearch:2.2.1
  labels:
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    elasticsearch.client.config.version: '0'
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es-logcentral/$${service_name}
  volumes_from:
    - elasticsearch-datavolume-client
  entrypoint:
    - /opt/rancher/bin/run.sh
  net: "container:elasticsearch-client"

kopf:
  image: rancher/kopf:v0.4.0
  labels:
    io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
  links:
    - elasticsearch-client:es-client
  ports:
    - 8090:80/tcp
  environment:
    - KOPF_ES_SERVERS=es-client:9200
    - KOPF_SERVER_NAME=es.dev
