elasticsearch-­master:
  image: rancher/elasticsearch­conf:v0.5.0
  labels:
    io.rancher.sidekicks: elasticsearch-­base-­master,elasticsearch­-datavolume­-master
    io.rancher.container.hostname_override: container_name
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es/elasticsearch­master
  volumes_from:
­    - elasticsearch-­datavolume-­master
  log_driver: ''
  log_opt: {}
elasticsearch-­datavolume­-master:
  labels:
    elasticsearch.datanode.config.version:'0'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: 'true'
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es/elasticsearch­master
  image: elasticsearch:2.2.1
  entrypoint: /bin/true
  volumes:
    - ­elasticsearch:/opt/rancher/bin
­    - elasticsearch:/usr/share/elasticsearch/config
­    - elasticsearch:/usr/share/elasticsearch/data
elasticsearch-­base-­master:
  labels:
    elasticsearch.master.config.version: '0'
    io.rancher.container.hostname_override: container_name
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=es/elasticsearch­master
  image: elasticsearch:2.2.1
  entrypoint:
­    - /opt/rancher/bin/run.sh
  volumes_from:
    ­- elasticsearch-­datavolume-­master
  net: "container:elasticsearch-­master"

elasticsearch-­datanode:
  labels:
    io.rancher.sidekicks: elasticsearch-­base­-datanode,elasticsearch-­datavolume-­datanode
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  image: rancher/elasticsearch­conf:v0.5.0
  links:
­    - elasticsearch­-master:es­master
  volumes_from:
    - ­elasticsearch­-datavolume­-datanode
  log_driver: ''
  log_opt: {}
elasticsearch­-datavolume-­datanode:
  labels:
    io.rancher.container.start_once: 'true'
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    elasticsearch.datanode.config.version: '0'
  image: elasticsearch:2.2.1
  links:
­    - elasticsearch­-master:es­master
  entrypoint:
    - /bin/true
  volumes:
    - logcentral:­/opt/rancher/bin
­    - logcentral:/usr/share/elasticsearch/config
­    - logcentral:/usr/share/elasticsearch/data
elasticsearch-­base­-datanode:
  labels:
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    elasticsearch.datanode.config.version: '0'
  image: elasticsearch:2.2.1
  links:
­    - elasticsearch­-master:es­master
  volumes_from:
    - elasticsearch­-datavolume-­datanode
  net: "container:elasticsearch-­datanode"

elasticsearch-client:
  labels:
    io.rancher.sidekicks: elasticsearch-­datavolume­-client,elasticsearch-­base­-client
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es/elasticsearch-­client
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
  image: rancher/elasticsearch­conf:v0.5.0
  links:
­    - elasticsearch­-master:es­master
  volumes_from:
    ­- elasticsearch-­datavolume­-client
  log_driver: ''
  log_opt: {}
elasticsearch­-datavolume-­client:
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es/elasticsearch­client
    io.rancher.container.start_once: 'true'
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
    elasticsearch.datanode.config.version: '0'
  image: elasticsearch:2.2.1
  links:
    - elasticsearch­-master:es­master
  entrypoint:
    - /bin/true
  volumes:
­    - logcentral:/usr/share/elasticsearch/config
­    - logcentral:/usr/share/elasticsearch/data
    - logcentral:/opt/rancher/bin
elasticsearch­-base-­client:
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=es/elasticsearch­client
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    elasticsearch.client.config.version: '0'
    io.rancher.container.hostname_override: container_name
  image: elasticsearch:2.2.1
  links:
    ­- elasticsearch­-master:es­master
  entrypoint:
­    - /opt/rancher/bin/run.sh
  volumes_from:
­    - elasticsearch­-datavolume­-client
  net: "container:elasticsearch­-client"

kopf:
  labels:
    # io.rancher.scheduler.affinity:host_label: graylogpool=yes
    io.rancher.container.hostname_override: container_name
  image: rancher/kopf:v0.4.0
  ports:
­    - 8090:80/tcp
  environment:
    KOPF_ES_SERVERS: 'es­client:9200'
    KOPF_SERVER_NAME: 'es.dev'
  links:
    ­- elasticsearch­client:es­client
