elasticsearch-datavolume-clients:
  scale: 2
  metadata:
    elasticsearch: &id002
      yml:
        cluster.name: graylog2
        network.host: _site_
        node.data: 'false'
        node.master: 'false'
        node.name: $${HOSTNAME}
elasticsearch-base-datanode:
  scale: 2
  metadata:
    elasticsearch: &id001
      yml:
        cluster.name: graylog2
        http.enabled: 'false'
        network.host: _site_
        node.data: 'true'
        node.master: 'false'
        node.name: $${HOSTNAME}
elasticsearch-datavolume-datanode:
  scale: 2
  metadata:
    elasticsearch: *id001
elasticsearch-clients:
  scale: 2
  metadata:
    elasticsearch: *id002
elasticsearch-datavolume-masters:
  scale: 2
  metadata:
    elasticsearch: &id003
      yml:
        cluster.name: graylog2
        network.host: _site_
        node.data: 'false'
        node.master: 'true'
        node.name: $${HOSTNAME}
kopf:
  scale: 1
elasticsearch-datanodes:
  scale: 2
  metadata:
    elasticsearch: *id001
elasticsearch-base-clients:
  scale: 2
  metadata:
    elasticsearch: *id002
elasticsearch-base-master:
  scale: 2
  metadata:
    elasticsearch: *id003
elasticsearch-masters:
  scale: 2
  metadata:
    elasticsearch: *id003
