app1:
  ports:
  - ":8080"
  restart: always
  environment:
    BUILDOUT_ZEO_CLIENT: 'True'
    BUILDOUT_ZEO_ADDRESS: zeo:8100
  tty: true
  image: eeacms/plone:5.0
  links:
  - zeo:zeo
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
zeo:
  expose:
  - "8100"
  restart: always
  tty: true
  image: eeacms/zeoserver
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
