version: '2'
catalog:
    name: Elasticsearch 6 engine 
    version: 6.1.1
    description: EEA Elasticsearch cluster to be used with elastic apps
    uuid: elastic6-engine-0

    questions:
        - variable: "cluster_name"
          type: "string"
          required: true
          label: "Cluster name"
          description: "Name of the Elasticsearch Cluster"
          default: "es-cluster"
        - variable: "host_labels"
          description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
          label: "Schedule on hosts with following host labels"
          type: "string"
          required: true
          default: elastic=yes
        - variable: "UPDATE_SYSCTL"
          label: "Update host sysctl:"
          description: |
            Set true to avoid vm.max_map_count errors.
            WARN: If set true, host param vm.max_map_count will be update to 262144.
          default: false
          required: true
          type: enum
          options:
            - false
            - true

        - variable: "master_heap_size"
          type: "string"
          required: true
          label: "Heap size (master nodes)"
          description: "Heap size to be allocated for Java (master nodes)"
          default: "512m"

        - variable: "master_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (master nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (master nodes)"
          default: 1073741824

        - variable: "data_heap_size"
          type: "string"
          required: true
          label: "Heap size (data nodes)"
          description: "Heap size to be allocated for Java (data nodes)"
          default: "512m"

        - variable: "data_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (data nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (data nodes)"
          default: 1073741824

        - variable: "client_heap_size"
          type: "string"
          required: true
          label: "Heap size (client nodes)"
          description: "Heap size to be allocated for Java (client nodes)"
          default: "512m"

        - variable: "client_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte (client nodes)"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size! (client nodes)"
          default: 1073741824

        - variable: "minimum_master_nodes"
          type: "int"
          required: true
          label: "# of minimum Master Nodes"
          description: "Set the number of required master nodes to reach quorum. Sets initial scale to this value as well"
          default: 1

        - variable: "initial_data_nodes"
          type: "int"
          required: true
          label: "# of initial data nodes"
          description: "Set the initial number of data nodes"
          default: 2

        - variable: "initial_client_nodes"
          type: "int"
          required: true
          label: "# of initial client nodes"
          description: "Set the initial number of client nodes"
          default: 1

        - variable: RO_USER
          description: "Read only username"
          label: "Read only username"
          type: "string"
          required: true
          default: "ro"
        - variable: RO_PASSWORD
          description: "Read only user password"
          label: "Read only user password"
          type: "password"
          required: true
          default: "rotest"
        - variable: RW_USER
          description: "RW Username"
          label: "Username with write access"
          type: "string"
          required: true
          default: "rw"
        - variable: RW_PASSWORD
          description: "Read/Write user password"
          label: "Password for RW Username"
          type: "password"
          required: true
          default: "rwtest"
        - variable: KIBANA_USER
          description: "KIBANA username"
          label: "kibana username"
          type: "string"
          required: true
          default: "kibana"
        - variable: KIBANA_PASSWORD
          description: "KIBANA user password"
          label: "kibana user password"
          type: "password"
          required: true
          default: "kibanatest"
        - variable: KEY_PASSWORD
          description: "ES key password"
          label: "ES https key password"
          type: "password"
          required: true
          default: "changeme"
        - variable: KEYSTORE_PASSWORD
          description: "ES keystore password"
          label: "ES keystore password"
          type: "password"
          required: true
          default: "changeme"




       

services:

  es-master:
    scale: ${minimum_master_nodes}

  es-worker:
    scale: ${initial_data_nodes}

  es-client:
    scale: ${initial_client_nodes}
  
  elastic-endpoint:
    external_ips:
      - 10.201.1.236



