esapp-aide-b:
  environment:
    VERSION_INFO: eeacms/esbootstrap:v1.2.7
    elastic_host: elastic
    AUTO_INDEXING: 'false'
    APP_CONFIG_DIRNAME: aide-b
  log_driver: ''
  ports:
    - '3000'
  labels:
    io.rancher.sidekicks: esbootstrap-data-config-aide-b
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  log_opt: {}
  image: eeacms/esbootstrap:v1.2.7
  volumes_from:
    - esbootstrap-data-config-aide-b
  links:
    - 'elastic:'

esbootstrap-data-config-aide-b:
  image: eeacms/esbootstrap-configs:latest
  environment:
    - github_repo=https://github.com/eea/eea.esbootstrap.configs
    - DEV_ENV=${dev_env}
  volumes:
    - "/code/config"
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name

esapp-aide-b-prelim:
  environment:
    VERSION_INFO: eeacms/esbootstrap:v1.2.7
    elastic_host: elastic
    AUTO_INDEXING: 'false'
    APP_CONFIG_DIRNAME: aide-b
  log_driver: ''
  ports:
    - '3000'
  labels:
    io.rancher.sidekicks: esbootstrap-data-config-aide-b-prelim
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  log_opt: {}
  image: eeacms/esbootstrap:v1.2.7
  volumes_from:
    - esbootstrap-data-config-aide-b
  links:
    - 'elastic:'

esbootstrap-data-config-aide-b-prelim:
  image: eeacms/esbootstrap-configs:latest
  environment:
    - github_repo=https://github.com/eea/eea.esbootstrap.configs
    - DEV_ENV=${dev_env}
  volumes:
    - "/code/config"
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: ${host_labels}
    io.rancher.container.hostname_override: container_name

elastic:
  external_links:
    - ${es_endpoint}
  image: rancher/dns-service
