.catalog:
  name: "eea-es-bootstrap-aide"
  version: "2.0"
  description: "EEA Elastic AIDE"
  uuid: eea-es-bootstrap-0
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: esbootstrap=yes
    - variable: dev_env
      label: "Define if stack in launched in development environment"
      description: "When set this to true, the configs will be pulled from github master branch each time the container is created."
      type: "boolean"
      required: false
      default: false
esapp-aide-b:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
esapp-aide-b-prelim:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
