version: "2"
services:
  rsync-client:
    image: eeacms/rsync:1.2
    labels:
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
    environment:
      TZ: "${TZ}"
      CRON_TASKS: "${CRON_TASKS}"
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-suggestions:/data/suggestions
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-archive:/var/lib/postgresql/archive
    - www-postgres-data:/var/lib/postgresql/data
    command:
    - client
  rsync-server:
    image: eeacms/rsync:1.1
    labels:
      io.rancher.scheduler.affinity:host_label: ${SYNC_HOST_LABELS}
    ports:
    - "2222:22"
    environment:
      TZ: "${TZ}"
      SSH_AUTH_KEY_POSTGRES: "${SSH_AUTH_KEY_POSTGRES}"
      SSH_AUTH_KEY_RSYNC: "${SSH_AUTH_KEY_RSYNC}"
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-suggestions:/data/suggestions
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-archive:/var/lib/postgresql/archive
    - www-postgres-data:/var/lib/postgresql/data
    command:
    - server
