version: '2'
services:
  master:
    image: eeacms/postgres:9.4-3.0
    labels:
      io.rancher.scheduler.affinity:host_label: ${POSTGRES_MASTER_HOST_LABELS}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DBUSER: "${POSTGRES_DBUSER}"
      POSTGRES_DBPASS: "${POSTGRES_DBPASS}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_CONFIG: "${POSTGRES_CONFIG}"
      POSTGRES_CRONS: "${POSTGRES_CRONS}"
      TZ: "${TZ}"
    volumes:
    - master-data:/var/lib/postgresql/data
    - dump:/postgresql.backup
    - archive:/var/lib/postgresql/archive
  replica:
    image: eeacms/postgres:9.4-3.0
    labels:
      io.rancher.scheduler.affinity:host_label: ${POSTGRES_REPLICA_HOST_LABELS}
    depends_on:
    - master
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_REPLICATE_FROM: "master"
      POSTGRES_CONFIG: "${POSTGRES_CONFIG}"
      RECOVERY_CONFIG: "${RECOVERY_CONFIG}"
      TZ: "${TZ}"
    volumes:
    - replica-data:/var/lib/postgresql/data
    - dump:/postgresql.backup
    - archive:/var/lib/postgresql/archive
volumes:
  master-data:
    driver: local
    per_container: true
  replica-data:
    driver: local
    per_container: true
  dump:
    driver: ${NFS_VOLUME_DRIVER}
  archive:
    driver: ${NFS_VOLUME_DRIVER}
