version: "2"
services:
  rsync-client:
    environment:
      CRON_TASKS: ${CRON_TASKS}
      TZ: ${TZ}
    labels:
      io.rancher.scheduler.affinity:host_label: ${SYNC_HOST_LABELS}
    command:
    - client
    image: eeacms/rsync
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-upstream-archive:/var/lib/postgresql/archive
  rsync-server:
    ports:
    - 2222:22/tcp
    environment:
      SSH_AUTH_KEY_POSTGRES: "${SSH_AUTH_KEY_POSTGRES}"
      SSH_AUTH_KEY_RSYNC: "${SSH_AUTH_KEY_RSYNC}"
      TZ: ${TZ}
    labels:
      io.rancher.scheduler.affinity:host_label: ${SYNC_HOST_LABELS}
    command:
    - server
    image: eeacms/rsync
    volumes:
    - www-blobstorage:/data/blobstorage
    - www-filestorage:/data/filestorage
    - www-downloads:/data/downloads
    - www-static-resources:/data/www-static-resources
    - www-eea-controlpanel:/data/eea.controlpanel
    - www-postgres-dump:/data/postgresql.backup
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-upstream-archive:/var/lib/postgresql/archive
volumes:
  www-postgres-data:
    external: true
  www-postgres-upstream-archive:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-blobstorage:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-filestorage:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-downloads:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-static-resources:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-eea-controlpanel:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-postgres-dump:
    external: true
    volume_driver: ${NFS_VOLUME_DRIVER}
