version: '2'
services:
  postgres:
    image: eeacms/postgres:9.4-2.0
    labels:
      io.rancher.scheduler.affinity:host_label: ${POSTGRES_HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_ne: eea.europa.eu.postgres=yes
      eea.europa.eu.postgres: "yes"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_DBUSER: "${POSTGRES_DBUSER}"
      POSTGRES_DBPASS: "${POSTGRES_DBPASS}"
      POSTGRES_CONFIG_MAX_CONNECTIONS: "${POSTGRES_CONFIG_MAX_CONNECTIONS}"
      POSTGRES_CONFIG_wal_level: "hot_standby"
      POSTGRES_CONFIG_max_wal_senders: "8"
      POSTGRES_CONFIG_wal_keep_segments: "256"
      POSTGRES_CONFIG_hot_standby: "on"
      POSTGRES_CONFIG_archive_mode: "on"
      POSTGRES_CONFIG_archive_command: " 'cp %p /var/lib/postgresql/archive/%f' "
      POSTGRES_CRONS: "${POSTGRES_CRONS}"
      TZ: "${TZ}"
    volumes:
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-dump:/postgresql.backup
    - www-postgres-replication-archive:/var/lib/postgresql/archive
volumes:
  www-postgres-data:
    external: ${VOLUMES_ENVIRONMENT_SCOPED}
    volume_driver: ${DB_VOLUME_DRIVER}
  www-postgres-dump:
    external: ${VOLUMES_ENVIRONMENT_SCOPED}
    volume_driver: ${NFS_VOLUME_DRIVER}
  www-postgres-replication-archive:
    external: ${VOLUMES_ENVIRONMENT_SCOPED}
    volume_driver: ${NFS_VOLUME_DRIVER}
