mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=${ROCKETCHAT_ROOT_URL}
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=${HUBOT_ROCKETCHAT_ROOM}
    - ROCKETCHAT_USER=${HUBOT_ROCKETCHAT_USER}
    - ROCKETCHAT_PASSWORD=${HUBOT_ROCKETCHAT_PASSWORD}
    - BOT_NAME=${HUBOT_BOT_NAME}
    - EXTERNAL_SCRIPTS=${HUBOT_EXTERNAL_SCRIPTS}
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
