mongo-data:
    image: docker.io/busybox
    volumes:
        - /data
    command: ['chown', '-R', '999:', '/data']
    labels:
        io.rancher.container.start_once: true
        io.rancher.container.hostname_override: container_name

es-data:
    image: docker.io/busybox
    volumes:
        - /data/elasticsearch
    command: ['chown', '-R', '105:100', '/data']
    labels:
       io.rancher.container.start_once: true
       io.rancher.container.hostname_override: container_name

postfix:
    restart: always
    image: eeacms/postfix:eionet
    volumes:
        - /etc/localtime:/etc/localtime:ro
    environment:
        - MTP_USER=${postfix_mtp_user}
        - MTP_PASS=${postfix_mtp_password}
        - MTP_HOST=logs.apps.eea.europa.eu
    labels:
       io.rancher.container.hostname_override: container_name

mongodb:
    image: docker.io/mongo:3.0.10
    restart: always
    command: "--smallfiles --quiet --logappend --logpath=/data/mongodb.log --dbpath=/data/db"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    volumes_from:
        - mongo-data
    labels:
       io.rancher.sidekicks: mongo-data
       io.rancher.container.hostname_override: container_name

elasticsearch:
    image: docker.io/elasticsearch:2.3.1
    restart: always
    volumes:
        - /etc/localtime:/etc/localtime:ro
    command: "elasticsearch -Des.cluster.name='graylog2' -Des.path.data=/data/elasticsearch -Des.path.logs=/data"
    environment:
        - ES_HEAP_SIZE=3g
    volumes_from:
        - es-data
    labels:
       io.rancher.sidekicks: es-data
       io.rancher.container.hostname_override: container_name

graylog-master:
    restart: always
    image: docker.io/eeacms/graylog2:2.0.2
    environment:
        - ENABLED_SERVICES=web,server
        - GRAYLOG_IS_MASTER=true
# Graylog settings
        - GRAYLOG_REST_TRANSPORT_URI=http://127.0.0.1:12900
        - GRAYLOG_WEB_ENDPOINT_URI=http://logs.apps.eea.europa.eu:12900
        - GRAYLOG_ELASTICSEARCH_CLUSTER_NAME=graylog2
        - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog2
# Graylog Email transport configuration
        - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
        - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=postfix
        - GRAYLOG_TRANSPORT_EMAIL_PORT=25
        - GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX=[graylog2]
        - GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL=noreply@eea.europa.eu
        - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://logs.apps.eea.europa.eu
        - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
        - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
        - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
# Graylog memory usage (-Xms min limit, -Xmx max limit)
        - GRAYLOG_HEAP_SIZE=-Xms2g -Xmx4g
# Graylog credentials
        - GRAYLOG_PASSWORD=${graylog_root_password}
        - GRAYLOG_PASSWORD_SECRET=${graylog_secret}
    ports:
        - "9000:9000/tcp"
        - "12900:12900/tcp"
    links:
        - "elasticsearch:elasticsearch"
        - "mongodb:mongodb"
        - "postfix:postfix"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    labels:
       io.rancher.container.hostname_override: container_name

graylog-client-1:
    restart: always
    image: docker.io/eeacms/graylog2:2.0.2
    environment:
        - GRAYLOG_IS_MASTER=false
        - ENABLED_SERVICES=server
# Graylog settings
        - GRAYLOG_REST_TRANSPORT_URI=http://127.0.0.1:12900
        - GRAYLOG_WEB_ENDPOINT_URI=http://logs.apps.eea.europa.eu:12900
        - GRAYLOG_ELASTICSEARCH_CLUSTER_NAME=graylog2
        - GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=graylog2
# Graylog Email transport configuration
        - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
        - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=postfix
        - GRAYLOG_TRANSPORT_EMAIL_PORT=25
        - GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX=[graylog2]
        - GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL=noreply@eea.europa.eu
        - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://logs.apps.eea.europa.eu
        - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
        - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
        - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
# Graylog memory usage (-Xms min limit, -Xmx max limit)
        - GRAYLOG_HEAP_SIZE=-Xms2g -Xmx4g
# Graylog credentials
        - GRAYLOG_PASSWORD=${graylog_root_password}
        - GRAYLOG_PASSWORD_SECRET=${graylog_secret}
    links:
        - "elasticsearch:elasticsearch"
        - "mongodb:mongodb"
        - "postfix:postfix"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    labels:
       io.rancher.container.hostname_override: container_name

loadbalancer:
    restart: always
    image: docker.io/eeacms/logcentralbalancer
    ports:
        - "1514:1514/tcp"
        - "12201:12201/udp"
    environment:
        - GRAYLOG_HOSTS=graylog-master,graylog-client-1
    volumes:
        - /etc/localtime:/etc/localtime:ro
    links:
        - "graylog-master"
        - "graylog-client-1"
    labels:
       io.rancher.container.hostname_override: container_name

fluentd:
    restart: always
    image: docker.io/eeacms/fluentd:logcentral
    links:
        - loadbalancer
    ports:
        - "5140:5140/udp"
    volumes:
        - /etc/localtime:/etc/localtime:ro
    labels:
       io.rancher.container.hostname_override: container_name
