version: '2'
catalog:
  name: "Rancher crontab container"
  description: "EEA rancher controlled crontab container to perform all cron tasks for docker containers"
  version: "1.0"
  uuid: "cronjobs-0"
  questions:
    - variable: "TZ"
      label: "Time zone"
      description: "Time zone"
      default: "Europe/Copenhagen"
      required: true
      type: "string"

services:
  container-crontab:
    health_check:
      interval: 20000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000