name: "Taskman"
description: "taskman.eionet.europa.eu - Redmine based Agile project management tool"
version: "2.0"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/rancher-alarms/
labels:
  io.rancher.certified: EEA

