version: "2"
catalog:
  name: "Rancher Alarms"
  description: "Application to monitor Rancher Services"
  version: "1.0"
  uuid: "rancher-alarms-0"
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "ALARM_POLL_INTERVAL"
    label: "Alarm poll interval"
    description: "How often does the application poll rancher for services, default 60000 ms"
    type: "int"
  - variable: "ALARM_MONITOR_INTERVAL"
    label: "Alarm check interval"
    description: "How often does the application poll services to check their status, default 15000ms"
    type: "int"
  - variable: "ALARM_MONITOR_HEALTHY_THRESHOLD"
    label: "Alarm healty checks threashold"
    description: "How many checks should the service be healty to close the alarm"
    type: "int"
  - variable: "ALARM_MONITOR_UNHEALTHY_THRESHOLD"
    label: "Alarm unhealty checks threashold"
    description: "How many checks should the service be unhealty to open the alarm"
    type: "int"
  - variable: "ALARM_FILTER"
    label: "Alarm filter"
    description: "What services should be monitored, ex app/*"
    type: "string"
  - variable: "ALARM_EMAIL_ADDRESSES"
    label: "Alarm email list"
    description: "To what emails should the alarms be sent"
    type: "string"
  - variable: "ALARM_EMAIL_FROM"
    label: "Alarm email from"
    default: "Alarm of a Night Watch <alarm@nightwatch.com>"
    description: "The from field on the alarms"
    type: "string"
  - variable: "ALARM_EMAIL_SUBJECT"
    label: "Alarm email subject"
    default: "[Rancher-Alarms] problems with #{serviceName}"
    description: "The subject field on the alarms"
    type: "string"
  - variable: "ALARM_EMAIL_TEMPLATE"
    label: "Alarm email body"
    default: "service #{serviceName} become #{monitorState}"
    description: "The body of the alarms"
    type: "string"
  - variable: "ALARM_SLACK_WEBHOOK_URL"
    label: "Alarm slack webhook url"
    description: "Slack webhook url - example: https://hooks.slack.com/services/YOUR_SLACK_UUID"
    type: "string"
  - variable: "ALARM_SLACK_CHANNEL"
    label: "Alarm slack channel"
    description: "Slack channel to post the alarms"
    type: "string"
  - variable: "ALARM_SLACK_BOTNAME"
    label: "Alarm slack botname"
    description: "Slack botname used to post the alarms"
    type: "string"
  - variable: "ALARM_SLACK_TEMPLATE"
    label: "Alarm slack template"
    description: "Alarm template - default 'Hey buddy! Your service #{serviceName} become #{healthyState}'"
    type: "string"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTFIX_RELAY"
    label: "Postfix relay"
    description: "Postfix SMTP relay"
    type: "string"
    default: "ironports.eea.europa.eu"
  - variable: "POSTFIX_PORT"
    label: "Postfix relay port"
    description: "Postfix SMTP relay port"
    type: "int"
    default: 8587
  - variable: "POSTFIX_USER"
    label: "Postfix user"
    description: "User used to send email"
    type: "string"
  - variable: "POSTFIX_PASS"
    label: "Postfix password"
    description: "Password used for MTP_USER"
    type: "password"

