version: "2"
catalog:
  name: "EEA WWW - Sync"
  description: "Sync EEA WWW blobs and static resources across Rancher Environments"
  version: "1.0-dev-rancher1"
  uuid: "www-sync-0"
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "RANCHER_ADDRESS"
    label: "Rancher URL"
    description: "Address of rancher to monitor: http://<HOST>:<PORT>/"
    type: "string"
  - variable: "RANCHER_PROJECT_ID"
    label: "Rancher environment id"
    description: "Environment id for the access key"
    type: "string"
  - variable: "RANCHER_ACCESS_KEY"
    label: "Rancher access key"
    description: "Api key to access rancher"
    type: "string"
  - variable: "RANCHER_SECRET_KEY"
    label: "Rancher secret key"
    description: "Secret key for api access key for rancher"
    type: "string"
  - variable: "ALARM_POLL_INTERVAL"
    label: "Alarm poll interval"
    description: "How often does the application poll rancher for services, default 60000 ms"
    type: "int"
  - variable: "ALARM_MONITOR_INTERVAL"
    label: "Alarm check interval"
    description: "How often does the application poll services to check their status, default 15000ms"
    type: "int"
  - variable: "ALARM_MONITOR_HEALTHY_THRESHOLD"
    default: 1
    label: "Alarm healty checks threashold"
    description: "How many checks should the service be healty to close the alarm"
    type: "int"
  - variable: "ALARM_MONITOR_UNHEALTHY_THRESHOLD"
    default: 1
    label: "Alarm unhealty checks threashold"
    description: "How many checks should the service be unhealty to open the alarm"
    type: "int"
  - variable: "ALARM_FILTER"
    label: "Alarm filter"
    description: "What services should be monitored, ex app/*"
    type: "string"
  - variable: "ALARM_EMAIL_ADDRESSES"
    label: "Alarm email list"
    default: "valentina.balan@eaudeweb.ro"
    description: "To what emails should the alarms be sent"
    type: "string"
  - variable: "ALARM_EMAIL_USER"
    label: "Email user"
    description: "SMTP server access user"
    type: "string"
  - variable: "ALARM_EMAIL_PASS"
    label: "Email user password"
    description: "SMTP server access user password"
    type: "string"
  - variable: "ALARM_EMAIL_SSL"
    label: "Connection to SMTP SSL or not"
    default: "false"
    description: "If the connection to SMTP server is secured"
    type: "string"
  - variable: "ALARM_EMAIL_SMTP_HOST"
    label: "SMTP HOST"
    description: "SMTP server host"
    default: "postfix"
    type: "string"
  - variable: "ALARM_EMAIL_SMTP_PORT"
    label: "SMTP PORT"
    default: 25
    description: "SMTP server port"
    type: "int"
  - variable: "ALARM_EMAIL_FROM"
    label: "Alarm email from"
    default: "Alarm of a Night Watch <alarm@nightwatch.com>"
    description: "The from field on the alarms"
    type: "string"
  - variable: "ALARM_EMAIL_SUBJECT"
    label: "Alarm email subject"
    description: "The subject field on the alarms - default [Rancher-Alarms] problems with #{serviceName}"
    type: "string"
  - variable: "ALARM_EMAIL_TEMPLATE"
    label: "Alarm email body"
    description: "The body of the alarms - default 'service #{serviceName} become #{monitorState}'"
    type: "string"
  - variable: "ALARM_SLACK_WEBHOOK_URL"
    label: "Alarm slack webhook url"
    description: "Slack webhook url - example: https://hooks.slack.com/services/YOUR_SLACK_UUID"
    type: "string"
  - variable: "ALARM_SLACK_CHANNEL"
    label: "Alarm slack channel"
    description: "Slack channel to post the alarms"
    type: "string"
  - variable: "ALARM_SLACK_BOTNAME"
    label: "Alarm slack botname"
    description: "Slack botname used to post the alarms"
    type: "string"
  - variable: "ALARM_SLACK_TEMPLATE"
    label: "Alarm slack template"
    description: "Alarm template - default 'Hey buddy! Your service #{serviceName} become #{healthyState}'"
    type: "string"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
