version: "2"
catalog:
  name: "EEA - Jenkins (Master)"
  description: "Jenkins Master"
  version: "2.89.3"
  uuid: "Jenkins-master-4"
  questions:
  - variable: "SERVER_NAME"
    label: "Server name"
    description: "DNS name for this deployment"
    default: "ci.eionet.europa.eu"
    type: "string"
    required: true
  - variable: "HOST_LABELS"
    label: "Schedule Jenkins Master on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1,key2=value2) to be used for scheduling the services."
    type: "string"
    required: true
    default: "jenkins-master=yes"
  - variable: "JENKINS_SESSION_TIMEOUT"
    label: "Jenkins Session Timeout"
    description: "Time in minutes that user is kept logged in with no activity"
    default: 240
    type: "int"
  - variable: "JENKINS_MASTER_PORT"
    label: "Jenkins Master Port"
    description: "Expose Jenkins master port on host"
    default: 8080
    type: "int"
  - variable: "JENKINS_SLAVE_PORT"
    label: "Jenkins Slave Port"
    description: "Expose Jenkins master port on host used by Jenkins Slaves to connect"
    default: 50000
    type: "int"
  - variable: "POSTFIX_RELAY"
    label: "Postfix relay"
    description: "Postfix SMTP relay"
    type: "string"
    default: "ironports.eea.europa.eu"
  - variable: "POSTFIX_PORT"
    label: "Postfix relay port"
    description: "Postfix SMTP relay port"
    type: "int"
    default: 8587
  - variable: "POSTFIX_USER"
    label: "Postfix user"
    description: "Postfix user name to connect to SMTP relay"
    type: "string"
  - variable: "POSTFIX_PASS"
    label: "Postfix password"
    description: "Postfix password to connect to SMTP relay"
    type: "password"
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    type: "string"
    required: true

services:
  master:
    scale: 1
    health_check:
      port: 8080
      interval: 60000
      initializing_timeout: 600000
      unhealthy_threshold: 5
      strategy: recreate
      healthy_threshold: 1
      response_timeout: 3000
  postfix:
    scale: 1
    health_check:
      port: 25
      interval: 60000
      initializing_timeout: 600000
      unhealthy_threshold: 5
      strategy: recreate
      response_timeout: 3000
      healthy_threshold: 1

