name: "EEA - Corpus Topic Modeling"
description: "Topic Modeling with EEA Corpus"
version: "0.5"
category: "Machine Learning"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.corpus
labels:
  io.rancher.certified: EEA
