version: "2"
catalog:
  name: "Matrix and Riot stack"
  description: "Matrix.org"
  version: "1.0"
  uuid: "matrix-riot-0"
  minimum_rancher_version: "v1.2.0"
  questions:

  - variable: "MATRIX_SERVER_NAME"
    label: "Matrix homeserver public FQDN"
    description: "The public url of matrix, used in federation and under which every user is saved"
    type: "string"
    required: true
  - variable: "MATRIX_REPORT_STATS"
    label: "Matrix.org report stats (yes/no)"
    default: "no"
    description: "Send data to matrix.org: hostname, synapse version & uptime, total_users, total_nonbridged users, total_room_count, daily_active_users, daily_active_rooms, daily_messages and daily_sent_messages."
    type: "string"
  - variable: "POSTGRES_DBUSER"
    label: "Matrix database user"
    default: "matrix"
    description: "Matrix postgres database user"
    type: "string"
  - variable: "POSTGRES_DBPASS"
    label: "Matrix database password"
    default: "matrix"
    description: "Matrix postgres database password"
    type: "password"
  - variable: "POSTGRES_DBNAME"
    label: "Matrix database name"
    default: "matrix"
    description: "Matrix postgres database name"
    type: "string"
  - variable: "MATRIX_EMAIL_FROM"
    label: "Matrix email FROM"
    default: "Riot EEA <eea@eea.com>"
    description: "Email used to send notifications from Matrix"
    type: "string"
  - variable: "MATRIX_URL"
    label: "Matrix https URL"
    default: "https://matrix.eea.europa.eu/"
    description: "Matrix https URL"
    type: "string"
    required: true
  - variable: "RIOT_URL"
    label: "Riot https URL"
    default: "https://riot.eea.europa.eu/"
    description: "Riot https URL"
    type: "string"
    required: true
  - variable: "MATRIX_IDENTITY_URL"
    label: "Matrix identity service https URL"
    default: "https://matrix-identity.eea.europa.eu/"
    description: "Matrix identity service https URL"
    type: "string"
    required: true
  - variable: "LDAP_HOST"
    label: "LDAP host"
    default: "ldap3.eionet.europa.eu"
    description: "LDAP EIONET host/ip"
    type: "string"
    required: true
  - variable: "LDAP_BINDDN"
    label: "LDAP binddn"
    default: "uid=user,ou=Users,o=EIONET,l=Europe"
    description: "The DN for the user to read from LDAP"
    type: "string"
    required: true
  - variable: "LDAP_BINDDN_PASS"
    label: "LDAP binddn password"
    description: "The password for the user to read from LDAP"
    type: "password"
    required: true
  - variable: "LDAP_BASEDN"
    label: "LDAP base DN"
    default: "ou=Users,o=EIONET,l=Europe"
    description: "LDAP BASE DN to give access to users"
    type: "string"
    required: true
  - variable: "LDAP_PORT"
    label: "LDAP port"
    default: "636"
    description: "Access port for LDAP"
    type: "int"
  - variable: "LDAP_TLS"
    label: "LDAP TLS enabled ( true/false)"
    default: "true"
    description: "LDAP TLS enabled true/false"
    type: "string"
  - variable: "LDAP_FILTER"
    label: "LDAP filter users"
    description: "Used to filter the users from LDAP with access "
    type: "string"
  - variable: "JAVA_OPTS"
    label: "Identity server JAVA options"
    description: "Identity server JAVA extra options"
    type: "string"


  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTFIX_RELAY"
    label: "Postfix relay"
    description: "Postfix SMTP relay"
    type: "string"
    default: "ironports.eea.europa.eu"
  - variable: "POSTFIX_PORT"
    label: "Postfix relay port"
    description: "Postfix SMTP relay port"
    type: "int"
    default: 8587
  - variable: "POSTFIX_USER"
    label: "Postfix user"
    description: "User used to send email"
    type: "string"
  - variable: "POSTFIX_PASS"
    label: "Postfix password"
    description: "Password used for MTP_USER"
    type: "password"
  - variable: "VOLUME_DRIVER"
    label: "Data volume driver"
    description: "Volume driver"
    default: "rancher-ebs"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "VOLUME_DRIVER_OPTS"
    label: "Data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"

