version: '2'
services:
  postgres:
    image: eeacms/postgres:9.4-2.0
    labels:
      io.rancher.scheduler.affinity:host_label: ${POSTGRES_REPLICA_HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_ne: eea.europa.eu.postgres=yes
      eea.europa.eu.postgres: "yes"
    links:
    - ${POSTGRES_MASTER}:master
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_CONFIG_MAX_CONNECTIONS: "${POSTGRES_CONFIG_MAX_CONNECTIONS}"
      POSTGRES_CONFIG_wal_level: "hot_standby"
      POSTGRES_CONFIG_max_wal_senders: "8"
      POSTGRES_CONFIG_wal_keep_segments: "256"
      POSTGRES_CONFIG_hot_standby: "on"
      POSTGRES_REPLICATE_FROM: "master"
      RECOVERY_CONFIG_primary_conninfo: " 'host=master port=5432 user=${POSTGRES_USER}' "
      RECOVERY_CONFIG_restore_command: " 'cp /var/lib/postgresql/archive/%f %p' "
      RECOVERY_CONFIG_archive_cleanup_command: " '${POSTGRES_ARCHIVE_CLEANUP}' "
      RECOVERY_CONFIG_trigger_file: " '/tmp/promote_to_master' "
      TZ: "${TZ}"
    volumes:
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-dump:/postgresql.backup
    - www-postgres-replication-archive:/var/lib/postgresql/archive
volumes:
  www-postgres-data:
    external: true
  www-postgres-dump:
    external: true
  www-postgres-replication-archive:
    external: true
