version: "2"
catalog:
  name: "EEA - PostgreSQL (Replica)"
  description: "Read-only PostgreSQL replica"
  version: "9.4-rancher1"
  uuid: "www-postgresql-replica-0"
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "POSTGRES_MASTER"
    label: "PostgreSQL Master"
    description: "Select PostgreSQL to replicate"
    type: "service"
    required: true
    default: "www-postgres-master/postgres"
  - variable: "POSTGRES_REPLICA_HOST_LABELS"
    label: "Schedule services on hosts with the following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling services"
    default: "www=yes,db=yes,db-replica=yes"
    type: "string"
    required: true
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTGRES_USER"
    label: "PostgreSQL user name"
    description: "PostgreSQL super user name"
    default: "postgres"
    type: "string"
    required: true
  - variable: "POSTGRES_PASSWORD"
    label: "PostgreSQL user password"
    description: "PostgreSQL super user password"
    default: "postgres"
    type: "password"
    required: true
  - variable: "POSTGRES_CONFIG_MAX_CONNECTIONS"
    label: "PostgreSQL maximum connections"
    description: "PostgreSQL maximum allowed connections"
    default: "150"
    type: "int"
    required: true
  - variable: "POSTGRES_ARCHIVE_CLEANUP"
    label: "PostgreSQL archive cleanup"
    description: "PostgreSQL archive cleanup command. Leave empty if you're going to scale this to more than one replica."
    default: "pg_archivecleanup /var/lib/postgresql/archive %r"
    type: "string"

services:
  postgres:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      strategy: recreate
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
