.catalog:
  name: "EEA — MoneyDigger"
  version: "v1.0-rancher1"
  description: |
   ELK-based app which shows how Redmine reported spent time and budget money is spent at EEA.
  minimum_rancher_version: v1.0.0