version: "2"
catalog:
  name: "Rancher Alarms"
  description: "Application to monitor Rancher Services"
  version: "1.0"
  uuid: "rancher-alarms-0"
  minimum_rancher_version: "v1.2.0"
  questions:
  - variable: "REDMINE_HOST"
    label: "Taskman hostname"
    default: "taskman.hostname"
    description: "The hostname of the redmine server"
    type: "string"
    required: true
  - variable: "REDMINE_URL"
    label: "Taskman URL"
    default: "https://taskman.hostname:taskman.port"
    description: "The Url where taskman will be accessed"
    type: "string"
    required: true
  - variable: "REDMINE_SERVER_LABEL"
    label: "Schedule redmine server on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the database service."
    type: "string"
    default: "taskman=yes"
  - variable: "REDMINE_DB_LABEL"
    label: "Schedule database on hosts with following host labels"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the database service."
    type: "string"
    default: "taskman=yes"
    required: true
  - variable: "TASKMAN_DEV"
    label: "Development/Testing installation"
    default: "yes"
    description: "Choose no only for production environment"
    type: "enum"
    options:
    - "yes"
    - "no"
    required: true
  - variable: "EXPOSE_PORT"
    label: "Port to expose on redmine server"
    description: "If left empty, will not be exposed on host"
    type: "int"
  - variable: "INCOMING_MAIL_API_KEY"
    label: "Incoming mail API key"
    description: " incoming emails API: Administration -> Settings -> Incoming email - API key"
    type: "string"
  - variable: "T_EMAIL_HOST"
    label: "Taskman email host"
    description: " Taskman email configuration: hostname"
    default: "gayal.eea.europa.eu"
    type: "string"
  - variable: "T_EMAIL_PORT"
    label: "Taskman email port"
    default: "993"
    description: " Taskman email configuration: port"
    type: "int"
  - variable: "T_EMAIL_USER"
    label: "Taskman email user"
    description: " Taskman email configuration: user"
    type: "string"
  - variable: "T_EMAIL_PASS"
    label: "Taskman email user password"
    description: " Taskman email configuration: user password"
    type: "password"
  - variable: "H_EMAIL_HOST"
    label: "Helpdesk email host"
    default: "outlook.office365.com"
    description: "Helpdesk email configuration: hostname"
    type: "string"
  - variable: "H_EMAIL_PORT"
    label: "Helpdesk email port"
    default: "993"
    description: "Helpdesk email configuration: port"
    type: "int"
  - variable: "H_EMAIL_USER"
    label: "Helpdesk email user"
    description: "Helpdesk email configuration: username"
    type: "string"
  - variable: "H_EMAIL_PASS"
    label: "Helpdesk email user password"
    description: "Helpdesk email configuration: user password"
    type: "password"
  - variable: "SYNC_API_KEY"
    label: "GitHub synchronisation API KEY"
    description: "Can be found under /settings?tab=repositories"
    type: "string"
    required: true
  - variable: "PLUGINS_URL"
    label: "Plugins location SVN URL"
    default: "https://eeasvn.eea.europa.eu/repositories/deployment/production/taskman"
    description: "The SVN URL that point to the folder where the PRO plugins are located"
    type: "string"
    required: true
  - variable: "PLUGINS_USER"
    label: "Plugins SVN User"
    description: "The SVN user"
    type: "string"
    required: true
  - variable: "PLUGINS_PASSWORD"
    label: "Plugins SVN User Password"
    description: "The SVN user password"
    type: "password"
    required: true
  - variable: "DB_NAME"
    label: "Redmine database name"
    description: "Mysql database name"
    type: "string"
    required: true
  - variable: "DB_USERNAME"
    label: "Redmine database username"
    description: "Mysql database username"
    type: "string"
    required: true
  - variable: "DB_PASSWORD"
    label: "Redmine database user password"
    description: "Mysql database user password"
    type: "password"
    required: true
  - variable: "DB_ROOT_PASSWORD"
    label: "Redmine database server root password"
    description: "Mysql server root password"
    type: "password"
    required: true
  - variable: "DB_DUMP_TIME"
    label: "Time to start database backup"
    default: "1720"
    description: "UTC time, formatted as a 4 digit number"
    type: "int"
    required: true
  - variable: "DB_DUMP_FREQ"
    label: "Frequency of backup"
    default: "1440"
    description: "Minutes between backups, set 1440 for daily"
    type: "int"
    required: true
  - variable: "DB_DUMP_FILENAME"
    label: "Database backup filename"
    default: "taskman_db_dump"
    description: "The name of the database dump file"
    type: "string"
    required: true
  - variable: "TZ"
    label: "Time zone"
    description: "Time zone"
    default: "Europe/Copenhagen"
    required: true
    type: "string"
  - variable: "POSTFIX_RELAY"
    label: "Postfix relay"
    description: "Postfix SMTP relay, not used in development mode"
    type: "string"
    default: "ironports.eea.europa.eu"
  - variable: "POSTFIX_PORT"
    label: "Postfix relay port"
    description: "Postfix SMTP relay port, not used in development mode"
    type: "int"
    default: 8587
  - variable: "POSTFIX_USER"
    label: "Postfix user"
    description: "User used to send email, not used in development mode"
    type: "string"
  - variable: "POSTFIX_PASS"
    label: "Postfix password"
    description: "Password used for MTP_USER, not used in development mode"
    type: "password"
  - variable: "RDM_FILES_VOLUMEDRIVER"
    label: "Redmine files volume driver"
    description: "Volume driver"
    default: "local"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "RDM_FILES_VOLUMEDRIVER_OPTS"
    label: "Redmine files volume driver options, should support at least 26GB"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 40".
    type: "multiline"
  - variable: "RDM_GITHUB_VOLUMEDRIVER"
    label: "Redmine github files volume driver"
    description: "Volume driver"
    default: "local"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "RDM_GITHUB_VOLUMEDRIVER_OPTS"
    label: "Redmine github files volume driver options, should support at least 4GB"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 10".
    type: "multiline"
  - variable: "RDM_SMALL_VOLUMEDRIVER"
    label: "Redmine plugins, temporary data volume driver"
    description: "Volume driver"
    default: "local"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "RDM_SMALL_VOLUMEDRIVER_OPTS"
    label: "Redmine plugins, temporary data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"
  - variable: "MYSQL_VOLUMEDRIVER"
    label: "MySQL data volume driver"
    description: "Volume driver"
    default: "local"
    type: "enum"
    options:
    - "rancher-ebs"
    - "rancher-nfs"
    - "local"
    required: true
  - variable: "MYSQL_VOLUMEDRIVER_OPTS"
    label: "MySQL data volume driver options"
    description: |
        Specify "driver_opts" key/value pair in the format "optionName: optionValue".
        E.g. for the `rancher-ebs` driver you should specify the required 'size' option like this: "size: 1".
    type: "multiline"

