version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      RABBITMQ_DEFAULT_USER: "${rabbitmq_default_user}"
      RABBITMQ_DEFAULT_PASS: "${rabbitmq_default_pass}"
      TZ: "${TZ}"
    volumes:
    - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
    driver: ${VOLUME_DRIVER}
    driver_opts:
      size: '1'
