name: Logcentral Logspout
description: |
  Glider Labs Logspout for docker logs to logcentral
version: 0.2.0-1
category: "Logging"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
