version: '2'
catalog:
  name: "EEA WWW - Volumes"
  description: "Prepare Docker volumes needed by EEA WWW"
  version: "1.0-rancher1"
  questions:
  - variable: "NFS_VOLUME_DRIVER"
    label: "NFS Volume Driver"
    description: "Docker volume driver to be used for shared volumes"
    default: "rancher-nfs"
    required: true
    type: "enum"
    options:
    - local
    - rancher-nfs
  - variable: "DB_VOLUME_DRIVER"
    label: "DB Volume Driver"
    description: "Docker volume driver to be used for PostgreSQL DB volumes"
    default: "local"
    required: true
    type: "enum"
    options:
    - local
    - rancher-nfs
  - variable: "NFS_VOLUME_HOST"
    label: "Schedule 'nfs-volumes' service on hosts with following host labels (scale=1)"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling 'nfs-volumes' service"
    default: "www=yes"
    type: "string"
  - variable: "DB_VOLUME_HOST"
    label: "Schedule 'db-volumes' service on hosts with following host labels (scale=global)"
    description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling 'db-volumes' service"
    default: "www=yes,db=yes"
    type: "string"
