name: "Rancher Alarms"
description: "Send notifications when something goes wrong in rancher"
version: "2.10.1-3.2"
category: "Supervision"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/rancher-alarms/
labels:
  io.rancher.certified: EEA

