.catalog:
  name: "eea-es-bootstrap-pam"
  version: "4.0.5"
  description: "PAM — Elastic app"
  uuid: eea-es-bootstrap-pam-5
  questions:
    - variable: es_endpoint
      description: "Select the service which represents the elasticsearch restful endpoint."
      label: "Elasticsearch endpoint"
      type: "service"
      required: true
    - variable: host_labels
      description: "Comma separated list of host labels (e.g. key1=value1, key2=value2) to be used for scheduling the services."
      label: "Schedule on hosts with following host labels"
      type: "string"
      required: true
      default: esbootstrap=yes
esapp:
  scale: 1
  health_check:
    port: 3000
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
