version: '2'
services:
  master:
    image: rancher/external-service
  backup:
    image: eeacms/postgres:9.6-3.1
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      POSTGRES_HOST: "master"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGHOST: "master"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_CRONS: "${POSTGRES_CRONS}"
      TZ: "${TZ}"
    volumes:
    - www-postgres-data:/var/lib/postgresql/data
    - www-postgres-dump:/postgresql.backup
    - www-postgres-archive:/var/lib/postgresql/archive
    stdin_open: true
    tty: true
    command:
    - cat
  memcached:
    image: memcached:1.5.7
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      TZ: "${TZ}"
    command:
    - "-m"
    - "${CACHE_SIZE}"

volumes:
  www-postgres-archive:
    external: true
  www-postgres-dump:
    external: true
  www-postgres-data:
    external: true
